CITIES: list[str] = sorted([
    # Africa
    "Abidjan", "Abuja", "Accra", "Addis Ababa", "Alexandria", "Algiers",
    "Antananarivo", "Asmara", "Bamako", "Bangui", "Banjul", "Bissau",
    "Brazzaville", "Cairo", "Cape Town", "Casablanca", "Conakry",
    "Dakar", "Dar es Salaam", "Djibouti", "Dodoma", "Douala",
    "Freetown", "Gaborone", "Harare", "Johannesburg", "Juba",
    "Kampala", "Khartoum", "Kigali", "Kinshasa", "Lagos",
    "Libreville", "Lilongwe", "Lomé", "Luanda", "Lusaka",
    "Malabo", "Maputo", "Maseru", "Mbabane", "Mogadishu",
    "Monrovia", "Moroni", "N'Djamena", "Nairobi", "Niamey",
    "Nouakchott", "Ouagadougou", "Porto-Novo", "Praia", "Rabat",
    "São Tomé", "Tripoli", "Tunis", "Windhoek", "Yamoussoukro", "Yaoundé",
    # Asia
    "Abu Dhabi", "Almaty", "Amman", "Ankara", "Ashgabat", "Astana",
    "Baghdad", "Baku", "Bangkok", "Beijing", "Beirut", "Bishkek",
    "Chennai", "Chongqing", "Colombo", "Damascus", "Dhaka", "Dili",
    "Doha", "Dubai", "Dushanbe", "Guangzhou", "Hanoi",
    "Ho Chi Minh City", "Hong Kong", "Hyderabad", "Islamabad",
    "Istanbul", "Jakarta", "Jerusalem", "Kabul", "Karachi", "Kathmandu",
    "Kolkata", "Kuala Lumpur", "Kuwait City", "Kyoto", "Lahore",
    "Macau", "Male", "Manama", "Manila", "Mumbai", "Muscat",
    "Naypyidaw", "New Delhi", "Nicosia", "Osaka", "Phnom Penh",
    "Pyongyang", "Riyadh", "Sanaa", "Seoul", "Shanghai", "Shenzhen",
    "Singapore", "Taipei", "Tashkent", "Tehran", "Thimphu",
    "Tbilisi", "Tokyo", "Ulaanbaatar", "Vientiane", "Wuhan",
    "Yangon", "Yerevan",
    # Europe
    "Amsterdam", "Andorra la Vella", "Athens", "Barcelona", "Belgrade",
    "Berlin", "Bern", "Bratislava", "Brussels", "Bucharest",
    "Budapest", "Chisinau", "Copenhagen", "Dublin", "Edinburgh",
    "Frankfurt", "Geneva", "Hamburg", "Helsinki", "Kyiv",
    "Lisbon", "Ljubljana", "London", "Luxembourg City", "Madrid",
    "Manchester", "Milan", "Minsk", "Monaco", "Munich",
    "Nice", "Oslo", "Paris", "Podgorica", "Prague",
    "Reykjavik", "Riga", "Rome", "Rotterdam", "San Marino",
    "Sarajevo", "Skopje", "Sofia", "Stockholm", "Tallinn",
    "Tirana", "Vaduz", "Valletta", "Venice", "Vienna",
    "Vilnius", "Warsaw", "Zagreb", "Zürich",
    # Americas — North & Central
    "Atlanta", "Austin", "Belmopan", "Boston", "Chicago",
    "Dallas", "Denver", "Guatemala City", "Havana", "Houston",
    "Kingston", "Las Vegas", "Los Angeles", "Managua", "Miami",
    "Mexico City", "Minneapolis", "Monterrey", "Montreal",
    "Nassau", "New Orleans", "New York", "Ottawa",
    "Panama City", "Philadelphia", "Phoenix", "Portland",
    "Puerto Vallarta", "Quebec City", "San Francisco", "San José",
    "San Juan", "Seattle", "Toronto", "Vancouver",
    "Washington DC",
    # Americas — South
    "Asunción", "Bogotá", "Brasília", "Buenos Aires",
    "Caracas", "Georgetown", "La Paz", "Lima",
    "Medellín", "Montevideo", "Paramaribo", "Port-au-Prince",
    "Port of Spain", "Quito", "Rio de Janeiro", "Santiago",
    "Santo Domingo", "São Paulo", "Sucre",
    # Oceania
    "Auckland", "Brisbane", "Canberra", "Christchurch",
    "Darwin", "Funafuti", "Honiara", "Melbourne",
    "Nuku'alofa", "Perth", "Pago Pago", "Palikir",
    "Papeete", "Port Moresby", "Port Vila", "Suva",
    "Sydney", "Tarawa", "Wellington",
    # Popular destinations not yet listed
    "Bali", "Cancún", "Cusco", "Florence", "Kraków",
    "Macchu Picchu", "Marrakech", "Mecca", "Medina",
    "Phuket", "Salzburg", "Santorini",
])
